default:
  image: rust:1.55
  tags:
    - rad1

cache:
  paths:
    - Cargo.lock
    - target/
    - .cargo/

variables:
  CARGO_HOME: "${CI_PROJECT_DIR}/.cargo/"
  CARGO_TERM_VERBOSE: "true"
  FLAGS: ""
  DEPLOY_RELEASE:
    value: "false"
    description: "Create a release build. Value can be 'true' or 'false' (default)"

workflow:
  rules:
    # Commit Tags are always release
    - if: $DEPLOY_RELEASE == "false" && $CI_COMMIT_TAG != ""
      variables:
        DEPLOY_RELEASE: "true"
    - if: $DEPLOY_RELEASE == "true" || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
      variables:
        FLAGS: "--release"

stages:
  - build
  - test
  - code-quality
  - deploy

cargo-build:
  stage: build
  script:
    - cargo build $FLAGS
  artifacts:
    paths:
      - target/release/rad1-cli
    expire_in: 1 week

cargo-test:
  stage: test
  script:
    - cargo test $FLAGS

check-formatting:
  stage: code-quality
  before_script:
    - rustup component add rustfmt
  script:
    - cargo fmt --all -- --check

lint:
  stage: code-quality
  before_script:
    - rustup component add clippy
  script:
    - cargo clippy -- -D warnings

pages:
  stage: deploy
  script:
    - cargo doc --no-deps --release
  after_script:
    - cp -R target/doc public
    - echo "/rad1/index.html /rad1/rad1/index.html 302" >> public/_redirects
    - echo "/rad1/ /rad1/rad1/ 302" >> public/_redirects
  artifacts:
    paths:
      - public
  rules:
    - if: $DEPLOY_RELEASE == "true"
