language: rust

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - windows

cache: cargo

jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true

before_script:
  - rustup component add rustfmt
  - rustup component add clippy

script:
  - cargo build --release --verbose
  - cargo test --verbose
  - cargo fmt --all -- --check
  - cargo clippy -- -D warnings

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: target/release/rad1
  on:
    tags: true
    os: linux
    rust: stable