[package]
name = "rad1"
version = "0.1.0"
authors = ["Sam Foster <slfotg@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
rand = "0.8.3"
shakmaty = "0.18.0"

[dev-dependencies]
test-case = "1.1.0"