[package]
name = "rad1-parsing"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pgn-reader = "0.19.0"
rand = "0.8.3"
rayon = "1.5.1"
shakmaty = "0.20.0"